#pragma once

enum XEventSource {
    ANALOG_LEFT_JOYSTICK_X,
    ANALOG_LEFT_JOYSTICK_Y,
    ANALOG_RIGHT_JOYSTICK_X,
    ANALOG_RIGHT_JOYSTICK_Y,

    ANALOG_RIGHT_TRIGGER,
    ANALOG_LEFT_TRIGGER,

    DPAD_X,
    DPAD_Y,

    BUTTON_A,
    BUTTON_B,
    BUTTON_X,
    BUTTON_Y,

    BUTTON_LEFT_TRIGGER,
    BUTTON_RIGHT_TRIGGER,

    BUTTON_MENU,
    BUTTON_VIEW,
    BUTTON_XBOX,
    BUTTON_LEFT_JOYSTICK,
    BUTTON_RIGHT_JOYSTICK,

    BUTTON_UPLOAD,

    SOURCE_UNKNOWN
};